nodeLinker: node-modules

npmAuthToken: "${NODE_AUTH_TOKEN:-fallback}"

logFilters:
  # https://yarnpkg.com/advanced/error-codes
  - code: YN0013
    level: discard
  - code: YN0076
    level: discard

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
