name: build

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths-ignore:
      - '.github/buildx-releases.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build
        uses: docker/bake-action@v2
        with:
          targets: build
