name: test

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths-ignore:
      - '.github/buildx-releases.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - lint
          - vendor-validate
          - license-validate
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Validate
        uses: docker/bake-action@v2
        with:
          targets: ${{ matrix.target }}

  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Test
        uses: docker/bake-action@v2
        with:
          targets: test-coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/clover.xml
